### ISSUE TITLE
styled-jsx not working correctly

### ISSUE THREAD

**Issue by tylersnyder** [developit/preact-styled-jsx-demo#1]
It looks like styles are not being scoped as expected with styled-jsx. I was able to get this working correctly again by switching the order of plugins in `.babelrc`

`"plugins": [
    "styled-jsx/babel",
    ["transform-react-jsx", { "pragma": "h" }]
  ]
`

**Comment by developit** [comment]
Fixed! Thanks for pointing that out!

**Comment by cdock1029** [comment]
Any reason this doesn't work with `preact-cli` ?

**Comment by developit** [comment]
You need to add a custom `.babelrc` or use preact.config.js to add the `styled-jsx/babel` plugin.

**Comment by cdock1029** [comment]
https://github.com/developit/preact-cli/issues/418
